steps:
- name: python
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    echo "$(git ls-tree -r main)"
    echo "$(git ls-tree -r master)"
    echo "$(git ls-tree -r HEAD main)"
  # - bash echo "$(git ls-tree -r branch)"
    # if [[ -n $(git diff --quiet main -- cloud-build/simple-app/app/) ]]; then
    #   echo "The file HAS changed"
    # else
    #   echo "No, the file did not change, we shall exit"
    #   exit 0
    # fi










