steps:
- name: python
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    echo "$(git ls-tree -r master)"
    echo "$COMMIT_SHA"
    echo "$REVISION_ID"
    echo "$(git diff-tree --no-commit-id --name-only $COMMIT_SHA -r)"
    echo "$BRANCH_NAME"
    echo "$(git log)"
    echo "$(git diff --name-only a9c7ca3e23719aa49a60dffcfe669e7ec1f4ba3b d08d54cc46ffa0f282edf0318d92a865663a3e85)"
    echo "$(git branch)"
    echo "$(git diff --pretty="" --name-only $COMMIT_SHA)"
    










