steps:
- name: python
  entrypoint: python
  args: 
  - bash echo "$BRANCH_NAME"
    if [[ -n app/** ]]; then
      bash echo "The file HAS changed"
    else
      bash echo "No, the file did not change, we shall exit"
      exit 0
    fi










