steps:
- name: python
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    echo "$(git ls-tree -r master)"
    echo "$(git log -m -1 --name-only --pretty=format:$COMMIT_SHA)"
    


    



    










