steps:
- name: python
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    echo "$(git ls-tree -r master)"
    echo "$(git log -1 --name-only --pretty=format:$COMMIT_SHA)"
    if [$(git log -1 --name-only --pretty=format:$COMMIT_SHA) == 'app/app.py']; then
      echo "The file HAS changed"
    else
      echo "No, the file did not change, we shall exit"
      exit 0
    fi


    



    










