steps:
- name: python
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    echo "$(git ls-tree -r master)"
    echo "$COMMIT_SHA"
    echo "$REVISION_ID"
    echo "$(git diff-tree --no-commit-id --name-only $COMMIT_SHA -r)"
    echo "$BRANCH_NAME"
    echo "$(git log -1)"
    echo "$(git rev-list master)"
    echo "$(git rev-list main)"
    echo "$(git rev-list HEAD)"
    echo "$(git log master)"
    echo "$(git log -1 --pretty=format:"%h" --follow Dockerfile)"
    echo "$(git log app/app.py)"
    echo "$(git log -1 --pretty=format:"%h")"

    
    



    










